<!--==============================content================================-->
<section id="content">         
  <div class="container_12">
    <div class="wrapper">
       <div class="grid_12">
           <div class="inner-block">
             <h2 class="padd-1">Privacy Policy</h2>
             <strong class="col-1">Sed tortor dui, suscipit non suscipit id, pretium vel nunc. Aliquam vel nulla in est elementum mattis eu eget diam. </strong>
             <p>Ut eu massa quam. In consequat, augue at pharetra placerat, velit tellus aliquam nibh; vitae vulputate lorem diam in turpis. Nullam venenatis mollis lorem adipiscing auctor. Proin orci quam; lacinia eu facilisis sed, posuere quis est. Cras posuere nunc quis augue dapibus tincidunt. Nulla bibendum nunc et mauris consequat aliquam condimentum urna congue. Fusce porta quam in tortor cursus commodo. In hac habitasse platea dictumst. Cras erat lorem, cursus quis commodo in, dignissim vel mauris? Proin id fringilla est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras et dolor turpis, sed fermentum odio. Proin feugiat orci sit amet lacus mattis vitae tempor diam suscipit.Sed feugiat commodo interdum? Proin eu ligula diam, eu placerat magna. Aliquam auctor augue id sem tempus aliquam. Phasellus viverra lectus at eros tincidunt feugiat consectetur justo porttitor. Sed ultrices, eros ut euismod fermentum, turpis ante accumsan augue, in volutpat purus nibh eu dolor. Donec ut mi tristique urna interdum convallis. Donec in nisl nec libero imperdiet semper at vel odio. Vivamus et pulvinar orci. Fusce dignissim suscipit sem non lacinia. Ut nec dolor eget risus lacinia tristique. Pellentesque ut lorem a nisl dignissim vehicula non pulvinar diam!Donec semper feugiat ultricies. Phasellus dolor nibh, feugiat eu placerat vitae, ultrices ornare orci. Sed tristique scelerisque justo, at dictum mauris auctor sit amet. Donec tristique feugiat cursus. Morbi et , id mattis odio. Donec venenatis posuere eleifend. Fusce porta tincidunt mauris quis tempor. Fusce sagittis facilisis neque eu tempus. Aliquam dapibus feugiat aliquam. Donec convallis tincidunt venenatis. Curabitur eget convallis mi? Quisque ut euismod orci. Nulla hendrerit porttitor dui in consequat. Sed tortor dui, suscipit non suscipit id, pretium vel nunc. </p>
             <strong class="col-1 dis-block top-1">Aliquam vel nulla in est elementum mattis eu eget diam. Ut eu massa quam. In consequat, augue at pharetra placerat, velit tellus aliquam nibh.</strong>
             <p>Nullam venenatis mollis lorem adipiscing auctor. Proin orci quam; lacinia eu facilisis sed, posuere quis est. Cras posuere nunc quis augue dapibus tincidunt. Nulla bibendum nunc et mauris consequat aliquam condimentum urna congue. Fusce porta quam in tortor cursus commodo. In hac habitasse platea dictumst. Cras erat lorem, cursus quis commodo in, dignissim vel mauris? Proin id fringilla est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras et dolor turpis, sed fermentum odio. Proin feugiat orci sit amet lacus mattis vitae tempor diam suscipit.Sed feugiat commodo interdum? Proin eu ligula diam, eu placerat magna. Aliquam auctor augue id sem tempus aliquam. Phasellus viverra lectus at eros tincidunt feugiat consectetur. Sed ultrices, eros ut euismod fermentum, turpis ante accumsan augue, in volutpat purus nibh eu dolor. Donec ut mi tristique urna interdum convallis. Donec in nisl nec libero imperdiet semper at vel odio. Vivamus et pulvinar orci. Fusce dignissim suscipit sem non lacinia. Ut nec dolor eget risus lacinia tristique. Pellentesque ut lorem a nisl dignissim vehicula non pulvinar diam!Donec semper feugiat ultricies. Phasellus dolor nibh, feugiat eu placerat vitae, ultrices ornare orci. Sed tristique scelerisque justo, at dictum mauris auctor sit amet. Donec tristique feugiat cursus. Morbi et nibh felis, id mattis odio. Donec venenatis posuere eleifend. Fusce porta tincidunt mauris quis tempor. Fusce sagittis facilisis neque eu tempus. Aliquam dapibus feugiat aliquam. Donec convallis tincidunt venenatis. Curabitur eget convallis mi? Quisque ut euismod orci. Nulla hendrerit porttitor dui in consequat. </p>
             <strong class="col-1 dis-block top-1">Sed tortor dui, suscipit non suscipit id, pretium vel nunc. Aliquam vel nulla in est elementum mattis eu eget diam. Ut eu massa quam.</strong>
             <p>In consequat, augue at pharetra placerat, velit tellus aliquam nibh; vitae vulputate lorem diam in turpis. Nullam venenatis mollis lorem adipiscing auctor. Proin orci quam; lacinia eu facilisis sed, posuere quis est. Cras posuere nunc quis augue dapibus tincidunt. Nulla bibendum nunc et mauris consequat aliquam condimentum urna congue. Fusce porta quam in tortor cursus commodo. In hac habitasse platea dictumst. Cras erat lorem, cursus quis commodo in, dignissim vel mauris? Proin id fringilla est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras et dolor turpis, sed fermentum odio. Proin feugiat orci sit amet lacus mattis vitae tempor diam suscipit.Sed feugiat commodo interdum? Proin eu ligula diam, eu placerat magna. Aliquam auctor augue id sem tempus aliquam. Phasellus viverra lectus at eros tincidunt feugiat consectetur justo porttitor. Sed ultrices, eros ut euismod fermentum, turpis ante accumsan augue, in volutpat purus nibh eu dolor. Donec ut mi tristique urna interdum convallis. Donec in nisl nec libero imperdiet semper at vel odio. Vivamus et pulvinar orci. Fusce dignissim suscipit sem non lacinia. Ut nec dolor eget risus lacinia tristique. Pellentesque ut lorem a nisl dignissim vehicula non pulvinar diam!Donec semper feugiat ultricies. Phasellus dolor nibh, feugiat eu placerat vitae, ultrices ornare orci. Sed tristique scelerisque justo, at dictum mauris auctor sit amet. Donec tristique feugiat cursus. Morbi et nibh felis, id mattis odio. Donec venenatis posuere eleifend. Fusce porta tincidunt mauris quis tempor. Fusce sagittis facilisis neque eu tempus. Aliquam dapibus feugiat aliquam. Donec convallis tincidunt venenatis. Curabitur eget convallis mi? Quisque ut euismod orci. Nulla hendrerit porttitor dui in consequat. Sed tortor dui, suscipit non suscipit id, pretium vel nunc. </p>
             <a href="#" class="pp">privacy@demolink.org</a>
           </div>
       </div>
    </div><!--the end of wrapper-->
  </div>
</section>